apiVersion: apps/v1
kind: Deployment
metadata:
  name: taa
  namespace: taa
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taa
  template:
    metadata:
      labels:
        app: taa
    spec:
      containers:
      - name: taa-php
        image: tuyendq99/php:v1
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.2"
        env:
        - name: APP_DEBUG
          valueFrom:
            configMapKeyRef:
              name: taa
              key: APP_DEBUG
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: taa
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: taa
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: taa
              key: DB_NAME   
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: taa
              key: DB_HOST
        ports:
        - containerPort: 9000
      - name: taa-nginx
        image: tuyendq99/nginx:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: taa-svc
spec:
  type: NodePort
  selector:
    app: taa
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
